const fs = require('fs');
const path = require('path');

// Read API URL from environment (Netlify will provide API_URL)
let apiUrl = process.env.API_URL || process.env.API_BASE_URL || 'http://localhost:5000';

// Normalize: remove trailing slash if present
apiUrl = apiUrl.replace(/\/+$/, '');

const outDir = path.join(__dirname, '..', 'frontend-vanilla', 'js');
if (!fs.existsSync(outDir)) fs.mkdirSync(outDir, { recursive: true });

const outFile = path.join(outDir, 'env.js');
const content = `// Generated by tools/write-env.js\nwindow.__API_BASE_URL = ${JSON.stringify(apiUrl)};\n`;

fs.writeFileSync(outFile, content, 'utf8');
console.log(`Wrote ${outFile} -> window.__API_BASE_URL = ${apiUrl}`);
